name = "Tinkerer's Quilt Modded (1.19)"
author = "Sisby folk"
version = "4.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74257a39c616938aed0b5764b244780ff7aef3fd6f7b535a9603f9d9f4a6dded"

[versions]
minecraft = "1.19.2"
quilt = "0.20.1"

[options]
acceptable-game-versions = ["1.19", "1.19.1", "1.19.2"]
datapack-folder = "/resources/packs/"
